project:
  type: website

website:
  title: "Victor Auger"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/VictorAuger
      - icon: twitter
        href: https://twitter.com/ViictorOG
format:
  html:
    theme: litera
    css: styles.css

