project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: https://victorauger.github.io/
  twitter-card:
    card-style: "summary_large_image"
  navbar:
    background: light
    left:
      - Victor Auger
      - Home
      - Publications.qmd
      - Research projects.qmd
      - Blog.qmd
      - Contact.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: false
