baseURL: "https://victorauger.github.io" 
title: Victor Auger
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: articles/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Teaching
          url: classes/
          weight: 3 
        - name: Resume
          url: CV.pdf

params:
    description: "I am a PhD Candidate in Social and Cognitive Psychology at the LAPSCO - UCA / CNRS."
    author: Victor Auger
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "02 Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Victor Auger
          subtitle: "I am a PhD Candidate in Social and Cognitive Psychology. I am interested in cognitive consequences of poverty and income inequality. I also work on visual representation, methods, and new practices."
          imageUrl: "photo.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: articles/
            - name: Talks
              url: talks/
            - name: Teaching
              url: classes/
            - name: Resume
              url: CV.pdf
    socialIcons:
        - name: hal
          url: https://hal.science/search/index/?q=*&authIdPerson_i=1252189
        - name: orcid
          url: https://orcid.org/0000-0002-8895-4591
        # - name: CV
        #   url: cv.pdf
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=vt447hoAAAAJ&hl=fr&oi=sra
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/VictorAuger
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat
        - name: Email
          url: mailto:victor.auger.ac@gmail.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Victor Auger"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
